social_network/dwitter/urls.py
from django.urls import path, include
from .views import dashboard, profile_list, profile, login

app_name = "dwitter"

urlpatterns = [
    path("",dashboard,name="dashboard"),
    path("profile_list/",profile_list,name="profile_list"),
    path("profile/<int:pk>", profile, name="profile"),
    
]

social_network/social_network/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("dwitter.urls")),
    path('auth/',include("django.contrib.auth.urls")),
]

social_network/dwitter/models.py
from xml.parsers.expat import model
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.
                                                

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    follows = models.ManyToManyField(
        "self",
        related_name="followed_by",
        symmetrical=False,
        blank=True
    )
    
    def __str__(self) -> str:
        return self.user.username
@receiver(post_save,sender=User)
def create_profile(sender,instance,created,**kwargs):
    if created:
        user_profile = Profile(user=instance)
        user_profile.save()
        user_profile.follows.add(instance.profile)
        user_profile.save()
# post_save.connect(create_profile,sender=User)
class Dweet(models.Model):
    user = models.ForeignKey(
        User,
        related_name = "dweets",
        on_delete=models.DO_NOTHING
    )
    body = models.CharField(max_length=140)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self) -> str:
        return (f"{self.user} "
            f"({self.created_at:%Y-%m-%d %H:%M}): "
            f"{self.body[:30]}...")

social_network/dwitter/forms.py
from django import forms
from django.forms import CharField, Textarea
from .models import Dweet
from django.contrib.auth.models import User
class DweetForm(forms.ModelForm):
    body = forms.CharField(
        required=True,
        widget=forms.Textarea(attrs={
            "placeholder": "Dweet something...",
            "class": "textarea is-success is-medium",
        }),
        label=""
        )
    class Meta:
        model = Dweet
        exclude = ("user",)
class LoginForm(forms.ModelForm):
    name = forms.CharField(max_length=244)
    password = forms.PasswordInput()
    class Meta:
        model = User
        exclude =("user",)

social_network/dwitter/views.py
from django.shortcuts import render,redirect
from .forms import DweetForm, LoginForm
from .models import Profile,User,Dweet

# Create your views here.
def dashboard(request):
    form = DweetForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            dweet = form.save(commit=False)
            dweet.user = request.user
            dweet.save()
            return redirect("dwitter:dashboard")
    followed_dweets = Dweet.objects.filter(
        user__profile__in=request.user.profile.follows.all()
    ).order_by("-created_at")
    return render(request,"dwitter/dashboard.html",{'form':form,"dweets": followed_dweets})
def profile_list(request):
    profiles = Profile.objects.exclude(user=request.user)
    return render(request, "dwitter/profile_list.html", {"profiles": profiles})
def profile(request,pk):
    if not hasattr(request.user, 'profile'):
        missing_profile = Profile(user=request.user)
        missing_profile.save()    
    user = User.objects.get(pk=pk)
    profile = Profile.objects.get(pk=pk)
    if request.method == "POST":
        current_user_profile = request.user.profile
        data = request.POST
        action = data.get("follow")
        if action == "follow":
            current_user_profile.follows.add(profile)
        elif action == "unfollow":
            current_user_profile.follows.remove(profile)
        current_user_profile.save()
    return render(request,"dwitter/profile.html",{
        "user": user,
        "profile" : profile,
    })
def login(request):
    return render(request,"dwitter/login.html")

social_network/dwitter/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dwitter</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
</head>

<body>
    <a href="{% url 'dwitter:dashboard' %} ">
        <section class="hero is-small is-success mb-4">
            <div class="hero-body">
                <h1 class="title is-1">Dwitter</h1>
                <p class="subtitle is-4">Your tiny social network built with django</p>
            </div>
        </section>

    </a>
    <div class="container">
        <div class="columns">
            {% block content %}

            {% endblock content %}

        </div>
    </div>

</body>

</html>

social_network/dwitter/templates/dwitter/dashboard.html
{% extends 'base.html' %}

{% block content %}

<div class="column">
    {% for dweet in dweets %}
    <div class="box">
        {{dweet.body}}
        <span class="is-small has-text-grey-light">
            ({{ dweet.created_at }} by {{ dweet.user.username }})
        </span>
    </div>
{% endfor %}
</div>

<div class="column is-one-third">
    <a href="{% url 'dwitter:profile_list' %}">
            <button class="button is-dark is-outlined is-three-quarters mb-3">
                All Profiles
            </button>
        </a>                                                                                            
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="button is-success is-fullwidth is-medium mt-5" type="submit">
            Dweet
        </button>
    </form>
</div>

{% endblock content %}

social_network/dwitter/templates/dwitter/profile.html
<!-- dwitter/templates/dwitter/profile_list.html -->

<!-- ... -->
{% extends 'base.html' %}
{% block content %}
<div class="columns container mt-1">
    <div class="column is-three-quarters">
        <h1 class="title is-1">{{ user }}'s Dweets</h1>
        <form method="post">
            {% csrf_token %}
            <div class="buttons has-addons">
                {% if profile in user.profile.follows.all %}
                <button class="button is-success is-static">Follow</button>
                <button class="button is-danger" name="follow" value="unfollow">Unfollow</button>
                {% else %}
                <button class="button is-success" name="follow" value="follow">Follow</button>
                <button class="button is-danger is-static">Unfollow</button>
                {% endif %}
            </div>
        </form>
        {% for dweet in profile.user.dweets.all %}
        <div class="box mt-2">
            {{ dweet.body }}
            <span class="is-small has-text-grey-light">
                ({{ dweet.created_at }})
            </span>
        </div>
        {% endfor %}
    </div>
    <div class="column">
        <a href="{% url 'dwitter:profile_list' %}">
            <button class="button is-dark is-outlined is-fullwidth">
                All Profiles
            </button>
        </a>
        <p class="title is-4 mb-1">{{user}} follows:</p>
        <ul>
            {% for user in profile.follows.all %}
            <li><a href="/profile/{{user.id}}">@{{ user|lower }}</a></li>
            {% endfor %}
        </ul>
        <p class="title is-4 mb-1">{{user}} is followed by:</p>
        <ul>
            {% for name in profile.followed_by.all %}
            <li><a href="/profile/{{name.id}}">@{{ name|lower }}</a></li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock content %}

social_network/dwitter/templates/dwitter/profile_list.html
<!-- dwitter/templates/dwitter/profile_list.html -->

{% extends 'base.html' %}

{% block content %}

<div class="column">

    {% for profile in profiles %}

    <div class="block">
        <div class="card">
            <a href="/profile/{{ profile.id }}">
                <div class="card-content">
                    <div class="media">
                        <div class="media-left">
                            <figure class="image is-48x48">
                                <img src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image">
                            </figure>
                        </div>
                        <div class="media-content">
                            <p class="title is-4">
                                {{ profile.user }}
                            </p>
                            <p class="subtitle is-6">
                                @{{ profile.user|lower }}
                            </p>
                        </div>
                    </div>
                </div>
            </a>
        </div>
    </div>

    {% endfor %}

</div>

{% endblock content %}